services:
  essenplaner:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: essenplaner
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - DEV_MODE=false
    volumes:
      - ./data:/app/data
